set user deleted at to now instead of removing from db
Code-4-Community/speak-for-the-trees-backend-v2 pull request #29
Opened 2021-03-29 21:37 UTC by oloveluck

2021-03-29 22:44 UTC, apradhan12 approved these changes
Looks good to me

2021-03-30 03:01 UTC, connernilsen approved these changes
Looks good 👍

2021-04-02 14:42 UTC, jackblanc approved these changes

2021-04-02 14:48 UTC, jackblanc requested changes
Just kidding https://c4cneuteams.slack.com/archives/C017922RBQQ/p1617069181004900

2021-04-26 16:47 UTC, merged